---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go-web-app1
  template:
    metadata:
      labels:
        name: go-web-app1
    spec:
      containers:
      - name: application
        image: alejandro048/go-web-app
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001